"use client";

import React, { useState } from "react";
import Loading from "../components/Loading";
import Image from "next/image";

{
  /* <div className="w-32 rounded overflow-hidden shadow-lg mt-4  ml-4  mb-4 hover:-translate-y-1 duration-300 cursor-pointer">
            <img
              className="w-full p-3"
              src="https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80"
              alt="Card Image"
            />
            <div className="px-2 py-2">
              <p className="text-gray-700 text-sm text-center">
                School & College
              </p>
            </div>
            <div className="px-6 py-1 flex justify-center">
              <button className="bg-orange-400 hover:bg-orange-700 duration-300 text-white font-bold py-2 px-4 rounded-full">
                Search
              </button>
            </div>
          </div> */
}

// export const metadata = {
//   title: "All Categories",
//   description: "Generated by create next app",
// };

const CategoriesData = [
  {
    id: "1",
    title: "school & collage",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "2",
    title: "Parking & Washing",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "3",
    title: "Water Suppliers",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "4",
    title: "Chasma Ghar",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "5",
    title: "Jewellery Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "6",
    title: "Petrol & Diesels",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "7",
    title: "Offset Press",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "8",
    title: "Cyber",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "9",
    title: "Animal Farm",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "10",
    title: "Travel & Tourism",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "11",
    title: "Meat Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "12",
    title: "Chasma Ghar",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "13",
    title: "Shoe Center",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "14",
    title: "Electricals",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "15",
    title: "Government Office",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "16",
    title: "Aluminum  House",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "17",
    title: "Insurance",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "18",
    title: "Mobile Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "19",
    title: "Shopping Mart",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "20",
    title: "Driving Center",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "20",
    title: "Cloth House",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "21",
    title: "Photo Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "22",
    title: "Photo Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "23",
    title: "Photo Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "24",
    title: "Photo Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "25",
    title: "Photo Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "26",
    title: "Photo Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
  {
    id: "27",
    title: "Photo Shop",
    img: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOj12MDd9&auto=format&fit=crop&w=750&q=80",
  },
];

const page = () => {
  return (
    <>
      <div className="flex justify-center items-center mt-16">
        <h2 className="font-bold text-4xl pt-10 mt-10">All Categories</h2>
      </div>

      <div className="flex justify-center items-center mt-20 ">
        <div
          className="w-4/5 justify-center items-center 
           flex flex-wrap
 gap-10"
        >
          {CategoriesData.map((categorie, index) => (
            <div
              className="w-32  rounded overflow-hidden shadow-lg mt-4   mb-4 hover:-translate-y-[3px] duration-300"
              key={index}
            >
              <Image
                className="w-full p-3"
                src={categorie.img}
                alt="Card Image"
              />
              <div className="">
                <p className="text-gray-700 text-sm text-center">
                  {categorie.title}
                </p>
              </div>
              <div className="px-6 py-1 flex justify-center">
                <button className="bg-orange-400 hover:bg-orange-700 duration-300 text-white font-bold py-2 px-4  rounded-full">
                  Search
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default page;
